# Generated by Django 5.0.4 on 2024-04-11 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='details',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='todo',
            name='dueDateTime',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
